import type { Challenge, OrientationPref } from "../../shared/types.js";

const N: OrientationPref[] = ["neutro"];
const GAY: OrientationPref[] = ["gay", "bi", "pan"];
const LES: OrientationPref[] = ["lesbiana", "bi", "pan"];
const HET: OrientationPref[] = ["hetero", "bi", "pan"];
const BI: OrientationPref[] = ["bi"];
const PAN: OrientationPref[] = ["pan"];
const ROM: OrientationPref[] = ["hetero", "gay", "lesbiana", "bi", "pan"];

/** Pack reetiquetado: el texto, el tipo, la orientación y el contentLevel coinciden. */
export const INITIAL_CHALLENGES: Challenge[] = [
  // === DRINK — el trago ES el reto (neutro salvo reglas explícitas) ===
  { id: "d01", type: "drink", intensity: 1, vibes: ["risas"], text: "{player}, brinda con {other} y di algo bonito (o falso, da igual).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d02", type: "drink", intensity: 2, vibes: ["risas", "competicion"], text: "{player}, si no puedes decir 3 países en 5 segundos, bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d03", type: "drink", intensity: 3, vibes: ["locura", "risas"], text: "{player}, bebe si alguna vez has mentido en este juego (spoiler: sí).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d04", type: "drink", intensity: 4, vibes: ["competicion"], text: "{player}, piedra-papel-tijera con {other}. El perdedor bebe doble.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "d05", type: "drink", intensity: 5, vibes: ["risas", "incomodidad"], text: "{player}, bebe cada vez que alguien diga tu nombre en los próximos 2 minutos.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "d06", type: "drink", intensity: 3, vibes: ["locura"], text: "{player}, bebe con la mano contraria a la que usas normalmente.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d07", type: "drink", intensity: 4, vibes: ["competicion", "risas"], text: "{player}, reto de miradas con {other}. El que parpadea primero bebe.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "d08", type: "drink", intensity: 6, vibes: ["locura", "competicion"], text: "{player}, bebe si no puedes mantener el equilibrio 10 seg con un pie.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "d09", type: "drink", intensity: 8, vibes: ["locura"], text: "{player}, shot de honor por el grupo. Sin excusas.", baseDrinks: 3, orientations: N, contentLevel: "medio" },
  { id: "d10", type: "drink", intensity: 7, vibes: ["locura", "competicion"], text: "{player}, bebe lo que el grupo decida. Democracia de copas.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d11", type: "drink", intensity: 3, vibes: ["nostalgia"], text: "{player}, bebe si extrañas algo de cuando eras más joven.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d12", type: "drink", intensity: 2, vibes: ["risas"], text: "{player}, bebe si has reído en los últimos 30 segundos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d13", type: "drink", intensity: 5, vibes: ["competicion"], text: "{player} vs {other}: quien tenga menos tragos en stats bebe 2.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d14", type: "drink", intensity: 9, vibes: ["locura"], text: "{player}, mezcla lo que quieras en un vaso y bebe un trago (con sentido común).", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d15", type: "drink", intensity: 6, vibes: ["incomodidad", "intimidad"], text: "{player}, bebe si esta noche te ha gustado alguien del grupo y no lo has dicho.", baseDrinks: 2, orientations: ROM, contentLevel: "medio" },
  { id: "d16", type: "drink", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, bebe si has tenido un crush con un tío de esta mesa (o con uno que os recuerde a alguien de aquí).", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "d17", type: "drink", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, bebe si has mirado más de la cuenta a una tía de esta mesa.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "d18", type: "drink", intensity: 10, vibes: ["locura", "competicion"], text: "{player}, todos los que estén por debajo de tu nivel te animan a beber. Tú decides cuánto.", baseDrinks: 3, orientations: N, contentLevel: "medio" },

  // === TRUTH ===
  { id: "t01", type: "truth", intensity: 1, vibes: ["risas", "nostalgia"], text: "{player}, ¿qué comida de la infancia volverías a comer ahora mismo?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t02", type: "truth", intensity: 2, vibes: ["risas"], text: "{player}, ¿qué superpoder inútil te gustaría tener?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t03", type: "truth", intensity: 3, vibes: ["incomodidad", "risas"], text: "{player}, ¿qué es lo más raro que has buscado en Google (versión apta para esta mesa)?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t04", type: "truth", intensity: 4, vibes: ["intimidad"], text: "{player}, ¿a quién del grupo le confiarías tu teléfono desbloqueado 1 minuto?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t05", type: "truth", intensity: 5, vibes: ["incomodidad"], text: "{player}, ¿qué mentira pequeña mantienes con alguien aquí?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "t06", type: "truth", intensity: 4, vibes: ["nostalgia"], text: "{player}, ¿qué canción te transporta a un momento concreto de tu vida?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t07", type: "truth", intensity: 4, vibes: ["risas"], text: "{player}, ¿qué personaje de ficción te representa cuando vas alto/a?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t08", type: "truth", intensity: 5, vibes: ["competicion"], text: "{player}, ¿quién del grupo crees que gana si hay pelea? Explica.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t09", type: "truth", intensity: 6, vibes: ["incomodidad"], text: "{player}, ¿has ghosteado a alguien? Cuenta la versión corta.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t10", type: "truth", intensity: 4, vibes: ["nostalgia", "risas"], text: "{player}, ¿qué trend de internet te pareció una locura total?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t11", type: "truth", intensity: 5, vibes: ["risas"], text: "{player}, ¿qué opinión impopular tienes sobre comida?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t12", type: "truth", intensity: 6, vibes: ["intimidad", "nostalgia"], text: "{player}, ¿cuál fue tu primer crush y qué edad tenías?", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "t13", type: "truth", intensity: 7, vibes: ["intimidad"], text: "{player}, ¿qué es lo que más te atrae de {other} (sin filtro de educación)?", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "t14", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, ¿qué valoras en alguien para algo más que amistad? Sé concreto.", baseDrinks: 1, orientations: ROM, contentLevel: "picante" },
  { id: "t15", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, describe tu tipo de chico con tres palabras atrevidas. O bebe.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "t16", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, describe tu tipo de chica con tres palabras atrevidas. O bebe.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "t17", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿tío o tía de esta mesa: a quién le harías el lío más peligroso y por qué?", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "t18", type: "truth", intensity: 9, vibes: ["intimidad"], text: "{player}, ¿con quién del grupo tendrías una cita si tuvieras que elegir? Di por qué sin esconderte.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "t19", type: "truth", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, cuenta tu lío gay más caótico (versión corta, sin doxxear a nadie que no esté aquí).", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },
  { id: "t20", type: "truth", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, cuenta tu lío con una tía más caótico (versión corta, sin doxxear a nadie que no esté aquí).", baseDrinks: 2, orientations: LES, contentLevel: "sin_limite" },
  { id: "t21", type: "truth", intensity: 10, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿cuál es tu fantasía más random con un tío? Sin juicio (mentira, hay juicio).", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },
  { id: "t22", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, ¿te enrollarías con más de un género esta noche si el universo dijera sí? Explica sin ensayo.", baseDrinks: 2, orientations: BI, contentLevel: "picante" },
  { id: "t23", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, olvida etiquetas: ¿quién de esta mesa te pone más y por qué (actitud, no solo cara)?", baseDrinks: 2, orientations: PAN, contentLevel: "picante" },
  { id: "t24", type: "truth", intensity: 7, vibes: ["incomodidad", "risas"], text: "{player}, ¿qué app borrarías del teléfono de {other} sin que se enterara?", baseDrinks: 1, orientations: N, contentLevel: "medio" },

  // === PHYSICAL NEUTRO (acción corporal, cero romance) ===
  { id: "pn01", type: "physical", intensity: 2, vibes: ["risas", "competicion"], text: "{player}, 10 flexiones o bebe. Tu cuerpo decide.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "pn02", type: "physical", intensity: 3, vibes: ["locura", "risas"], text: "{player}, baila 20 segundos sin música. El grupo marca el ritmo a palmas.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn03", type: "physical", intensity: 3, vibes: ["risas"], text: "{player}, camina como si el suelo quemara hasta tu sitio.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn04", type: "physical", intensity: 4, vibes: ["nostalgia", "risas"], text: "{player}, recrea un baile de cuando eras adolescente. 15 segundos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn05", type: "physical", intensity: 5, vibes: ["locura", "competicion"], text: "{player}, mantén una postura ridícula 30 seg. Si te mueves, bebe.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "pn06", type: "physical", intensity: 4, vibes: ["risas"], text: "{player}, imita a {other} (voz y gestos) hasta que alguien acierte.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn07", type: "physical", intensity: 6, vibes: ["competicion"], text: "{player} vs {other}: abdominales en 30 seg. El que hace menos bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn08", type: "physical", intensity: 5, vibes: ["competicion"], text: "{player}, equilibra algo en la cabeza 15 seg (lo que sea seguro).", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn09", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, habla solo con gestos 1 minuto. Si hablas, bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn10", type: "physical", intensity: 7, vibes: ["competicion"], text: "{player}, salta lo más alto que puedas 5 veces seguidas.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn11", type: "physical", intensity: 8, vibes: ["risas", "locura"], text: "{player}, haz la voltereta o el intento más patético que puedas.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn12", type: "physical", intensity: 8, vibes: ["locura"], text: "{player}, 20 saltos de tijera o bebe el doble.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn13", type: "physical", intensity: 9, vibes: ["locura", "competicion"], text: "{player}, plank 45 segundos. Si caes, bebe y repites 15 seg.", baseDrinks: 3, orientations: N, contentLevel: "medio" },
  { id: "pn14", type: "physical", intensity: 6, vibes: ["locura"], text: "{player}, intenta tocar el suelo con las palmas sin doblar las rodillas.", baseDrinks: 2, orientations: N, contentLevel: "suave" },

  // === PHYSICAL GAY + PICANTE / SIN LÍMITE (acción + contexto gay de verdad) ===
  { id: "pg01", type: "physical", intensity: 6, vibes: ["locura", "intimidad"], text: "{player}, perrea 20 segundos como si {other} fuera el único tío que existe en la pista. Si te cortas, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg02", type: "physical", intensity: 7, vibes: ["locura", "risas"], text: "{player}, 12 sentadillas lentas y sucias. En cada una, un piropo de sauna a un chico del grupo (o al aire si no hay tíos).", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg03", type: "physical", intensity: 6, vibes: ["intimidad", "incomodidad"], text: "{player}, imita un ligue gay de after: mirada, sonrisa y mano en el hombro de {other} 5 seg. Si {other} dice no, solo la mirada.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg04", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, pose de calendario fitness 15 segundos. Actitud de camiseta mojada, camiseta puesta. Mira a los chicos.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg05", type: "physical", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, body roll + mirada pícara 10 segundos dedicados a {other}. Si te ríes, trago.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg06", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, 8 pasos de pasarela eligiendo arquetipo (twink, oso, daddy…) y desfila para los tíos de la mesa.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg07", type: "physical", intensity: 8, vibes: ["locura", "incomodidad"], text: "{player}, shirt-lift de 3 segundos (sube y baja la camiseta) mirando a {other}. O 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg08", type: "physical", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, baila pegado al aire 20 seg como si {other} te sujetara la cintura en un after.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg09", type: "physical", intensity: 8, vibes: ["competicion", "intimidad"], text: "{player}, plancha 20 seg. Mientras, di en voz alta tu tipo de chico con detalle. Si caes, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg10", type: "physical", intensity: 6, vibes: ["risas", "intimidad"], text: "{player}, recrea un primer beso de peli gay (con el aire o con tu mano). 10 segundos de drama.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg11", type: "physical", intensity: 7, vibes: ["incomodidad", "locura"], text: "{player}, siéntate, ábrete de piernas, inclínate y dile a {other} «ven aquí» con la cabeza. Si no puedes de la risa, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg12", type: "physical", intensity: 8, vibes: ["locura", "competicion"], text: "{player}, 10 flexiones y en cada una un verbo atrevido que te gustaría oír de un tío. El grupo puntúa.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg13", type: "physical", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, slow-motion de quitar la camiseta SIN quitártela (el tease cuenta). 15 seg. O trago triple.", baseDrinks: 3, orientations: GAY, contentLevel: "sin_limite" },
  { id: "pg14", type: "physical", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, siéntate en el regazo de {other} 5 segundos (ambos ok) o 3 tragos. Actitud de ligue gay, no de IKEA.", baseDrinks: 3, orientations: GAY, contentLevel: "sin_limite" },

  // === PHYSICAL LESBIANA + PICANTE ===
  { id: "pl01", type: "physical", intensity: 6, vibes: ["locura", "intimidad"], text: "{player}, perrea 20 segundos como si {other} fuera la única tía de la pista. Si te cortas, bebes.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl02", type: "physical", intensity: 7, vibes: ["locura", "risas"], text: "{player}, 12 sentadillas lentas. En cada una, un piropo de bar a una chica del grupo (o al aire si no hay tías).", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl03", type: "physical", intensity: 6, vibes: ["intimidad", "incomodidad"], text: "{player}, imita un ligue lésbico de after: mirada, sonrisa y mano en el hombro de {other} 5 seg. Si dice no, solo la mirada.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl04", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, pose de portada soft 15 segundos. Actitud de «te como con los ojos». Mira a las chicas.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl05", type: "physical", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, body roll + mirada pícara 10 segundos dedicados a {other}. Si te ríes, trago.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl06", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, 8 pasos de pasarela eligiendo vibe (fem, butch, soft…) y desfila para las tías de la mesa.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl07", type: "physical", intensity: 8, vibes: ["locura", "incomodidad"], text: "{player}, sube el dobladillo o enseña un hombro 3 segundos mirando a {other}. O 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl08", type: "physical", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, baila pegada al aire 20 seg como si {other} te sujetara la cintura en un after.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl09", type: "physical", intensity: 8, vibes: ["competicion", "intimidad"], text: "{player}, plancha 20 seg. Mientras, di en voz alta tu tipo de chica con detalle. Si caes, bebes.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl10", type: "physical", intensity: 6, vibes: ["risas", "intimidad"], text: "{player}, recrea un primer beso de peli lésbica (con el aire o con tu mano). 10 segundos de drama.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl11", type: "physical", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, tease de quitar una capa SIN quitártela 15 seg. O trago triple.", baseDrinks: 3, orientations: LES, contentLevel: "sin_limite" },
  { id: "pl12", type: "physical", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, siéntate en el regazo de {other} 5 segundos (ambas ok) o 3 tragos. Actitud de ligue, no de metro.", baseDrinks: 3, orientations: LES, contentLevel: "sin_limite" },

  // === PHYSICAL HETERO + PICANTE ===
  { id: "ph01", type: "physical", intensity: 6, vibes: ["locura", "intimidad"], text: "{player}, perrea 20 segundos mirando a alguien del género que te atrae en esta mesa. Si te cortas, bebes.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph02", type: "physical", intensity: 7, vibes: ["locura", "risas"], text: "{player}, 12 sentadillas lentas. En cada una, un piropo hetero de discoteca (el clásico malo cuenta).", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph03", type: "physical", intensity: 6, vibes: ["intimidad", "incomodidad"], text: "{player}, imita un ligue hetero de after: mirada, sonrisa y mano en el hombro de {other} 5 seg. Si dice no, solo la mirada.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph04", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, pose de anuncio de colonia 15 segundos. Mira a {other} como en un spot caro y tonto.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph05", type: "physical", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, body roll + mirada pícara 10 segundos dedicados a {other}. Si te ríes, trago.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph06", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, 8 pasos de pasarela «pareja de película hetero» y desfila para {other}.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph07", type: "physical", intensity: 8, vibes: ["locura", "incomodidad"], text: "{player}, shirt-lift o enseña un hombro 3 segundos mirando a {other}. O 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph08", type: "physical", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, baila pegado/a al aire 20 seg como si {other} te sujetara la cintura.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph09", type: "physical", intensity: 8, vibes: ["competicion", "intimidad"], text: "{player}, plancha 20 seg. Mientras, di tu tipo del género opuesto con detalle. Si caes, bebes.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph10", type: "physical", intensity: 6, vibes: ["risas", "intimidad"], text: "{player}, recrea un primer beso de romcom hetero (con el aire o con tu mano). 10 segundos.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph11", type: "physical", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, tease de quitar una capa SIN quitártela 15 seg. O trago triple.", baseDrinks: 3, orientations: HET, contentLevel: "sin_limite" },
  { id: "ph12", type: "physical", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, siéntate en el regazo de {other} 5 segundos (ambos ok) o 3 tragos.", baseDrinks: 3, orientations: HET, contentLevel: "sin_limite" },

  // === VOTE ===
  { id: "v01", type: "vote", intensity: 2, vibes: ["risas"], text: "Votación: ¿quién es más probable que llegue tarde a su propia boda? El más votado bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v02", type: "vote", intensity: 3, vibes: ["risas", "competicion"], text: "Votación: ¿quién tiene el mejor sentido del humor de copas?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v03", type: "vote", intensity: 4, vibes: ["incomodidad", "risas"], text: "Votación: ¿quién es más probable que mande un mensaje de madrugada a un ex?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "v04", type: "vote", intensity: 5, vibes: ["competicion"], text: "Votación: ¿quién ganaría en un concurso de comer rápido?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v05", type: "vote", intensity: 5, vibes: ["intimidad"], text: "Votación: ¿quién tiene más carisma sin esfuerzo?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "v06", type: "vote", intensity: 4, vibes: ["nostalgia"], text: "Votación: ¿quién ha cambiado más desde que lo conocéis?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v07", type: "vote", intensity: 5, vibes: ["risas"], text: "Votación: ¿quién tiene el mejor y el peor gusto musical?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v08", type: "vote", intensity: 6, vibes: ["competicion"], text: "Votación: ¿quién del grupo es el más competitivo? (ironía pura).", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "v09", type: "vote", intensity: 7, vibes: ["intimidad", "risas"], text: "Votación: ¿quién es más guapo/a esta noche? (sin debate eterno).", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "v10", type: "vote", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "Votación: ¿quién daría el mejor ligue gay de esta mesa?", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "v11", type: "vote", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "Votación: ¿quién daría el mejor ligue lésbico de esta mesa?", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "v12", type: "vote", intensity: 6, vibes: ["locura"], text: "Votación: ¿quién debería ser el DJ del resto de la noche?", baseDrinks: 1, orientations: N, contentLevel: "suave" },

  // === KARAOKE ===
  { id: "k01", type: "karaoke", intensity: 2, vibes: ["risas", "nostalgia"], text: "{player}, canta el estribillo de la primera canción que te venga a la cabeza.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k02", type: "karaoke", intensity: 3, vibes: ["risas"], text: "{player}, canta «Feliz cumpleaños» como ópera.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k03", type: "karaoke", intensity: 4, vibes: ["locura", "risas"], text: "{player}, canta una canción inventada sobre {other}.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "k04", type: "karaoke", intensity: 5, vibes: ["competicion"], text: "{player}, duelo de canto con {other}. El grupo decide. Perdedor bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k05", type: "karaoke", intensity: 5, vibes: ["nostalgia"], text: "{player}, canta una canción de cuando tenías 15 años.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k06", type: "karaoke", intensity: 6, vibes: ["locura"], text: "{player}, canta el último mensaje de voz que recibiste (tono musical). Tú eliges cuál.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k07", type: "karaoke", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, canta una balada romántica mirando a {other}.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "k08", type: "karaoke", intensity: 8, vibes: ["locura"], text: "{player}, rap improvisado de 30 seg sobre esta fiesta.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k09", type: "karaoke", intensity: 4, vibes: ["risas"], text: "{player}, imita el estilo de canto de un artista famoso (sin decir quién).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k10", type: "karaoke", intensity: 5, vibes: ["nostalgia", "risas"], text: "{player}, canta el tema de una serie que veías de niño.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k11", type: "karaoke", intensity: 7, vibes: ["locura", "risas"], text: "{player}, canta el estribillo de la canción más vergonzosa de tu playlist como si fueras de talent show.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k12", type: "karaoke", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, canta 20 segundos de una canción de ligue gay (tú eliges) dedicándosela a {other}.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },

  // === PHONE (humor, sin doxxear a terceros inocentes) ===
  { id: "f01", type: "phone", intensity: 2, vibes: ["risas"], text: "{player}, muestra la foto más random de tu galería (sin explicar mucho).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f02", type: "phone", intensity: 3, vibes: ["risas"], text: "{player}, enseña tu fondo de pantalla y explica por qué (mentira permitida).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f03", type: "phone", intensity: 4, vibes: ["risas"], text: "{player}, enseña la app que más usas y defiéndela como TED talk.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f04", type: "phone", intensity: 5, vibes: ["nostalgia"], text: "{player}, muestra la foto más antigua que tengas en el teléfono.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f05", type: "phone", intensity: 5, vibes: ["risas"], text: "{player}, cambia tu estado de WhatsApp a lo que el grupo decida por 10 min.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f06", type: "phone", intensity: 6, vibes: ["incomodidad", "risas"], text: "{player}, lee el nombre del último chat que TÚ elijas (no doxxees a alguien que no está).", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f07", type: "phone", intensity: 7, vibes: ["incomodidad"], text: "{player}, muestra tu historial de búsqueda de hoy (o bebe si no quieres).", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "f08", type: "phone", intensity: 6, vibes: ["risas", "locura"], text: "{player}, graba un audio de 5 seg diciendo algo random. El grupo decide si lo envías al chat de ESTA fiesta.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "f09", type: "phone", intensity: 7, vibes: ["risas"], text: "{player}, selfie grupal con filtro absurdo. No subir obligatorio: solo enseñar.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f10", type: "phone", intensity: 8, vibes: ["incomodidad"], text: "{player}, deja que {other} lea un mensaje que TÚ elijas de tu chat.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "f11", type: "phone", intensity: 7, vibes: ["competicion"], text: "{player}, el grupo pone timer: consigue 3 likes en una story en 2 min o bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "f12", type: "phone", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, enseña (tú eliges) una foto de galería que sea medio sospechosa. El grupo inventa el contexto.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },

  // === COUPLE — romance/contacto. Si coupleChallengesEnabled=false no salen. ===
  { id: "cr01", type: "couple", intensity: 4, vibes: ["intimidad"], text: "{player}, mira a {other} 15 seg sin hablar. Quien sonría primero bebe.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "cr02", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, di 3 cosas que te gustan de {other} (sin repetir «eres majo»).", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "cr03", type: "couple", intensity: 7, vibes: ["intimidad"], text: "{player}, masajea los hombros de {other} 15 segundos (ambos ok) o bebe.", baseDrinks: 1, orientations: ROM, contentLevel: "picante" },
  { id: "cr04", type: "couple", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, baila lento con {other} 30 seg (o lo que salga). Si no hay feeling, 2 tragos.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "cr05", type: "couple", intensity: 8, vibes: ["intimidad"], text: "{player}, beso en la mejilla de {other}. O bebe si el momento no da.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "cr06", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, body shot simulado con {other} (sin alcohol en cuerpos si no queréis). O 3 tragos.", baseDrinks: 3, orientations: ROM, contentLevel: "sin_limite" },
  { id: "cr07", type: "couple", intensity: 10, vibes: ["intimidad", "locura"], text: "{player}, lo que el grupo pida entre tú y {other}. Límite: lo que ambos acepten. Si no, 3 tragos.", baseDrinks: 3, orientations: ROM, contentLevel: "sin_limite" },

  { id: "cg01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, susurra al oído de {other} un piropo gay de discoteca. Si no se te ocurre, bebe.", baseDrinks: 1, orientations: GAY, contentLevel: "medio" },
  { id: "cg02", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, finge que {other} es tu crush de Grindr en una peli 15 seg (ambos ok).", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "cg03", type: "couple", intensity: 9, vibes: ["intimidad"], text: "{player}, elige con {other}: beso (lo que ambos acepten), verdad sucia de tíos o 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },

  { id: "cl01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, susurra al oído de {other} un piropo de tía a tía. Si no se te ocurre, bebe.", baseDrinks: 1, orientations: LES, contentLevel: "medio" },
  { id: "cl02", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, finge que {other} es tu crush de un after lésbico 15 seg (ambas ok).", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "cl03", type: "couple", intensity: 9, vibes: ["intimidad"], text: "{player}, elige con {other}: beso (lo que ambas acepten), verdad sucia de tías o 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "sin_limite" },

  { id: "ch01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, susurra a {other} un piropo hetero de mal gusto a propósito. Si flipa, bebes tú.", baseDrinks: 1, orientations: HET, contentLevel: "medio" },
  { id: "ch02", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, finge que {other} es tu crush de romcom 15 seg (ambos ok).", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ch03", type: "couple", intensity: 9, vibes: ["intimidad"], text: "{player}, elige con {other}: beso (lo que ambos acepten), verdad sucia hetero o 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "sin_limite" },

  { id: "cb01", type: "couple", intensity: 5, vibes: ["intimidad"], text: "{player}, dile a {other} qué género te come más la cabeza esta noche. Sin ensayo.", baseDrinks: 1, orientations: BI, contentLevel: "medio" },
  { id: "cb02", type: "couple", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, elige a {other} y di en voz alta si tu crush de ahora es más «tío», «tía» o «las dos cosas».", baseDrinks: 2, orientations: BI, contentLevel: "picante" },
  { id: "cb03", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player} y {other}: 20 seg de flirteo sin importar género. Si os cortáis, 2 tragos.", baseDrinks: 2, orientations: BI, contentLevel: "sin_limite" },

  { id: "cp01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, ignora etiquetas y dile a {other} qué te atrae de su forma de estar.", baseDrinks: 1, orientations: PAN, contentLevel: "medio" },
  { id: "cp02", type: "couple", intensity: 8, vibes: ["intimidad"], text: "{player}, flirtea 15 seg con {other} como si el género no existiera. Solo vibra.", baseDrinks: 1, orientations: PAN, contentLevel: "picante" },
  { id: "cp03", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player} y {other}: el grupo pide un gesto atrevido. Solo si ambos aceptan; si no, 2 tragos.", baseDrinks: 2, orientations: PAN, contentLevel: "sin_limite" },

  // === STRIP ===
  { id: "s01", type: "strip", intensity: 5, vibes: ["risas", "incomodidad"], text: "{player}, quita un accesorio (reloj, calcetín, gorra…). O bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "s02", type: "strip", intensity: 5, vibes: ["risas"], text: "{player}, quita los zapatos de forma cinematográfica.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "s03", type: "strip", intensity: 6, vibes: ["risas"], text: "{player}, ponte 1 prenda de {other} encima de la tuya.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "s04", type: "strip", intensity: 6, vibes: ["risas", "locura"], text: "{player}, cambia una prenda con {other} (accesorio vale). Sin drama.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "s05", type: "strip", intensity: 7, vibes: ["incomodidad", "risas"], text: "{player}, quita la capa de ropa que el grupo vote. Consentimiento primero; si no, 2 tragos.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s06", type: "strip", intensity: 8, vibes: ["locura", "intimidad"], text: "{player}, strip de una prenda con la máxima dramaturgia posible. O bebe.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s07", type: "strip", intensity: 7, vibes: ["competicion", "risas"], text: "{player} vs {other}: quien se quite más accesorios en 10 seg gana. Perdedor bebe.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s08", type: "strip", intensity: 8, vibes: ["incomodidad"], text: "{player}, describe tu outfit como pasarela. El grupo decide si quitas algo o bebes.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s09", type: "strip", intensity: 9, vibes: ["locura"], text: "{player}, ruleta mental: una capa de ropa o trago triple.", baseDrinks: 3, orientations: N, contentLevel: "sin_limite" },
  { id: "s10", type: "strip", intensity: 10, vibes: ["locura", "competicion"], text: "{player}, el grupo cuenta capas. Quitas N o bebes N tragos. Tú pones el límite.", baseDrinks: 2, orientations: N, contentLevel: "sin_limite" },
  { id: "s11", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, {other} elige qué prenda quitas o qué bebes. Veto libre.", baseDrinks: 3, orientations: ROM, contentLevel: "sin_limite" },
  { id: "s12", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, baile de strip 15 seg para los tíos de la mesa o 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "s13", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, baile de strip 15 seg para las tías de la mesa o 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "s14", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, baile de strip 15 seg dedicado a {other} (vibe hetero) o 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "s15", type: "strip", intensity: 9, vibes: ["locura", "intimidad"], text: "{player}, quita una prenda como si estuvieras en un after gay. O 3 tragos.", baseDrinks: 3, orientations: GAY, contentLevel: "sin_limite" },
  { id: "s16", type: "strip", intensity: 9, vibes: ["locura", "intimidad"], text: "{player}, quita una prenda como si estuvieras en un after lésbico. O 3 tragos.", baseDrinks: 3, orientations: LES, contentLevel: "sin_limite" },

  // === MINIGAME — reglas claras, tags honestos (NO gay/físico/picante de mentira) ===
  { id: "m01", type: "minigame", intensity: 2, vibes: ["competicion", "risas"], text: "Mini-juego: {player} y {other}, piedra-papel-tijera al mejor de 3. Perdedor bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m02", type: "minigame", intensity: 3, vibes: ["competicion"], text: "Mini-juego: {player}, di un color. {other} dice animal. Tú un país. Sin pensar. Si tardas, bebes.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m03", type: "minigame", intensity: 3, vibes: ["risas"], text: "Mini-juego: todos a la vez, sacad la lengua. El último bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m04", type: "minigame", intensity: 4, vibes: ["risas", "nostalgia"], text: "Mini-juego: {player}, adivina la canción que {other} tararea.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m05", type: "minigame", intensity: 3, vibes: ["risas"], text: "Mini-juego: {player}, di «ruleta del trago» entre cada palabra durante 30 seg.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m06", type: "minigame", intensity: 4, vibes: ["nostalgia", "risas"], text: "Mini-juego: {player}, adivina qué serie veía {other} de niño con 3 pistas.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m07", type: "minigame", intensity: 4, vibes: ["risas"], text: "Mini-juego: {player}, imita un videojuego clásico solo con sonidos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m08", type: "minigame", intensity: 5, vibes: ["competicion", "risas"], text: "Mini-juego: {player} vs {other}, pulgar a pulgar. 3 rondas.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m09", type: "minigame", intensity: 5, vibes: ["competicion", "locura"], text: "Mini-juego: {player}, aguanta 20 seg con un cubito en la mano o bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m10", type: "minigame", intensity: 5, vibes: ["risas"], text: "Mini-juego: {player}, ojos cerrados, identifica a {other} solo por la voz.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m11", type: "minigame", intensity: 5, vibes: ["competicion"], text: "Mini-juego: {player}, el grupo pide tocarse nariz, oreja, codo… sin manos. 20 seg.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m12", type: "minigame", intensity: 6, vibes: ["risas", "locura"], text: "Mini-juego: {player}, cuenta hasta 20 sustituyendo los múltiplos de 3 por «ruleta».", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m13", type: "minigame", intensity: 6, vibes: ["competicion", "risas"], text: "Mini-juego: {player}, lanza algo blando al aire. Acierta dónde dice el grupo o bebe.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m14", type: "minigame", intensity: 6, vibes: ["risas", "competicion"], text: "Mini-juego: {player} vs todos. Tú lanzas un «yo nunca» de fiesta light. Si alguien ya lo hizo, bebe. Si nadie, tú.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m15", type: "minigame", intensity: 6, vibes: ["locura"], text: "Mini-juego: {player}, no puedes tocar tu vaso con la mano derecha hasta la siguiente ronda.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m16", type: "minigame", intensity: 7, vibes: ["locura"], text: "Mini-juego: {player}, habla con voz de robot hasta la siguiente ronda.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m17", type: "minigame", intensity: 7, vibes: ["competicion"], text: "Mini-juego: cuenta atrás de 10. {player} y {other} a la vez. Quien llegue a 0 primero gana; el otro bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m18", type: "minigame", intensity: 7, vibes: ["locura", "risas"], text: "Mini-juego: {player}, categoría random. 5 cosas en 10 segundos o bebes.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m19", type: "minigame", intensity: 8, vibes: ["competicion", "locura"], text: "Mini-juego: todos. Manos al centro, el último en quitar bebe. {player} da la señal.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m20", type: "minigame", intensity: 8, vibes: ["locura", "risas"], text: "Mini-juego: todos copian el movimiento de {player}. El que se ría bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },

  // === EXPANSIÓN — mismos criterios: texto concreto, tags honestos, consentimiento, salida con trago ===
  { id: "d19", type: "drink", intensity: 2, vibes: ["risas"], text: "{player}, brinda con el vaso más lejos de ti. Si lo tiras, bebes doble. Con cuidado.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d20", type: "drink", intensity: 3, vibes: ["competicion", "risas"], text: "{player}, nombra 5 marcas de bebida en 8 segundos o bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d21", type: "drink", intensity: 4, vibes: ["risas"], text: "{player}, bebe si no recuerdas qué bebió {other} la última vez. El grupo hace de juez.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d22", type: "drink", intensity: 3, vibes: ["locura"], text: "{player}, un trago con los ojos cerrados. Si te ríes, otro.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d23", type: "drink", intensity: 5, vibes: ["competicion"], text: "{player}, el grupo elige 1, 2 o 3. Esos tragos. Tú puedes vetar el 3 y beber 1.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d24", type: "drink", intensity: 4, vibes: ["incomodidad", "risas"], text: "{player}, bebe si tu último like de Instagram te daría vergüenza leerlo en voz alta. Honor system.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "d25", type: "drink", intensity: 4, vibes: ["competicion"], text: "{player} vs {other}: quien tenga el vaso más lleno bebe 1. Empate: los dos un sorbo.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d26", type: "drink", intensity: 6, vibes: ["locura"], text: "{player}, inventa un «cóctel» con lo que hay en la mesa y bebe un sorbo. Nada raro ni peligroso.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d27", type: "drink", intensity: 3, vibes: ["risas"], text: "{player}, bebe si has dicho «en serio» o «espera» en los últimos 5 minutos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d28", type: "drink", intensity: 2, vibes: ["risas", "nostalgia"], text: "{player}, brinda por el cumple de la mesa. Si no hay, por quien más lo merezca esta noche. Un trago.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d29", type: "drink", intensity: 5, vibes: ["competicion", "locura"], text: "{player}, 3 sorbos al ritmo de las palmas del grupo. Si fallas el tempo, uno extra.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d30", type: "drink", intensity: 3, vibes: ["risas"], text: "{player}, bebe si no sabes el signo de {other} (o si te lo inventas y fallas).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d31", type: "drink", intensity: 6, vibes: ["locura", "risas"], text: "{player}, da una vuelta al vaso alrededor de tu cabeza (sin derramar) y bebe. Circo de salón.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d32", type: "drink", intensity: 5, vibes: ["competicion"], text: "{player}, elige a alguien: esa persona decide si bebes 1 o 2. Democracia tóxica.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d33", type: "drink", intensity: 6, vibes: ["incomodidad", "risas"], text: "{player}, bebe si esta noche ya has pensado «me voy a casa» y sigues aquí.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d34", type: "drink", intensity: 4, vibes: ["risas"], text: "{player}, choca los vasos con {other} por abajo (brindis de peli). Si lo hacéis mal, los dos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },

  { id: "t25", type: "truth", intensity: 3, vibes: ["risas", "incomodidad"], text: "{player}, ¿cuál es tu red flag más evidente… y cómo la niegas igual?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t26", type: "truth", intensity: 2, vibes: ["risas"], text: "{player}, ¿qué mentira pequeña has dicho hoy (aunque sea «ya salgo»)?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t27", type: "truth", intensity: 4, vibes: ["risas", "competicion"], text: "{player}, ¿quién de esta mesa sería peor compañero de piso y por qué?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t28", type: "truth", intensity: 3, vibes: ["incomodidad", "risas"], text: "{player}, ¿qué canción tienes en repeat y te da vergüenza admitirlo?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t29", type: "truth", intensity: 5, vibes: ["incomodidad"], text: "{player}, ¿qué conversación de esta noche estás fingiendo que no te ha picado?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t30", type: "truth", intensity: 4, vibes: ["nostalgia"], text: "{player}, ¿cuál fue tu peor corte de pelo y en qué año?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t31", type: "truth", intensity: 5, vibes: ["risas"], text: "{player}, ¿qué skill inútil tienes que nadie de aquí sabía?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t32", type: "truth", intensity: 6, vibes: ["incomodidad", "intimidad"], text: "{player}, ¿a quién de esta mesa le pedirías consejo de verdad… y a quién no?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "t33", type: "truth", intensity: 4, vibes: ["risas"], text: "{player}, ¿cuál es tu pedido de comida más vergonzoso a las 3 de la mañana?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t34", type: "truth", intensity: 6, vibes: ["nostalgia", "intimidad"], text: "{player}, ¿qué amistad de tu vida te cambió el humor para siempre?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t35", type: "truth", intensity: 7, vibes: ["incomodidad"], text: "{player}, ¿qué habrías cancelado de esta noche si pudieras volver atrás 2 horas?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "t36", type: "truth", intensity: 5, vibes: ["competicion", "risas"], text: "{player}, ¿quién de aquí gana un concurso de «cara de póker» y quién se delata solo?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t37", type: "truth", intensity: 7, vibes: ["intimidad"], text: "{player}, ¿qué detalle pequeño de {other} te parece atractivo y nunca lo has dicho?", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "t38", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿cuál es tu movimiento de ligue que funciona… y el que es un crimen?", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "t39", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, describe el after gay perfecto en tres reglas. Sin PowerPoint.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "t40", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, describe el after lésbico perfecto en tres reglas. Sin PowerPoint.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "t41", type: "truth", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, ¿cuál es tu peor cita hetero (versión corta, sin doxxear)?", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "t42", type: "truth", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿qué tío de esta mesa (o que os recuerde a uno) te pondría más nervioso en un after?", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },
  { id: "t43", type: "truth", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿qué tía de esta mesa (o que os recuerde a una) te pondría más nerviosa en un after?", baseDrinks: 2, orientations: LES, contentLevel: "sin_limite" },
  { id: "t44", type: "truth", intensity: 7, vibes: ["intimidad"], text: "{player}, esta noche: ¿te tira más un tío, una tía o el caos de no elegir?", baseDrinks: 2, orientations: BI, contentLevel: "picante" },

  { id: "pn15", type: "physical", intensity: 3, vibes: ["competicion"], text: "{player}, 15 sentadillas. El grupo cuenta. Si paras, bebes.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "pn16", type: "physical", intensity: 4, vibes: ["locura", "risas"], text: "{player}, camina de espaldas hasta el punto que el grupo señale (con cuidado) o bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn17", type: "physical", intensity: 5, vibes: ["risas"], text: "{player}, recorre la mesa en cámara lenta como si fueras un trailer de Netflix. 15 segundos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn18", type: "physical", intensity: 4, vibes: ["competicion", "risas"], text: "{player}, aguanta 20 segundos a la pata coja con un vaso en la mano (vacío vale). Si caes, bebes.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "pn19", type: "physical", intensity: 6, vibes: ["locura"], text: "{player}, 10 jumping jacks gritando un número distinto en cada uno. Si te lías, bebes.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn20", type: "physical", intensity: 5, vibes: ["risas", "nostalgia"], text: "{player}, recrea el baile de tu primer instituto 15 segundos. Sin piedad.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn21", type: "physical", intensity: 7, vibes: ["competicion"], text: "{player} vs {other}: wall-sit 20 segundos. Quien se levante primero bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn22", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, habla 30 segundos como presentador del tiempo mientras haces squats suaves.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn23", type: "physical", intensity: 8, vibes: ["competicion", "locura"], text: "{player}, 8 burpees patéticos o 2 tragos. El intento cuenta si sudas vergüenza.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn24", type: "physical", intensity: 5, vibes: ["risas"], text: "{player}, camina como cangrejo 5 pasos. Si no puedes, bebes y haces 2.", baseDrinks: 1, orientations: N, contentLevel: "suave" },

  { id: "pg15", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, 15 segundos de «mirada de baño de discoteca gay» a {other}. Si parpadeas de la risa, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg16", type: "physical", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, enseña el antebrazo o la clavícula 5 seg como si fuera un after de tíos. O 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg17", type: "physical", intensity: 7, vibes: ["locura"], text: "{player}, 10 pasos de vogue flojo dedicados a los chicos de la mesa. Si te cortas, bebes.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg18", type: "physical", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, acércate a {other} y dile al oído un verbo atrevido (ambos ok). Si no, 2 tragos y se acaba.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },

  { id: "pl13", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, 15 segundos de «mirada de baño de discoteca lésbica» a {other}. Si parpadeas de la risa, bebes.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl14", type: "physical", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, enseña un hombro o el cuello 5 seg con actitud de after de tías. O 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl15", type: "physical", intensity: 7, vibes: ["locura"], text: "{player}, 10 pasos de pasarela soft dedicados a las chicas de la mesa. Si te cortas, bebes.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl16", type: "physical", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, acércate a {other} y dile al oído un verbo atrevido (ambas ok). Si no, 2 tragos y se acaba.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },

  { id: "ph13", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, 15 segundos de mirada de «te invito a un gin» a {other}. Si te ríes, bebes.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph14", type: "physical", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, enseña un hombro o el antebrazo 5 seg como anuncio hetero barato. O 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph15", type: "physical", intensity: 7, vibes: ["locura"], text: "{player}, 10 pasos de pasarela de romcom dedicados a {other}. Si te cortas, bebes.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph16", type: "physical", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, acércate a {other} y dile al oído un piropo hetero ridículo (ambos ok). Si no, 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },

  { id: "v13", type: "vote", intensity: 3, vibes: ["risas"], text: "Votación: ¿quién es más probable que pida comida ahora mismo? El más votado bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v14", type: "vote", intensity: 4, vibes: ["risas", "competicion"], text: "Votación: ¿quién tiene el peor historial de «ya salgo»?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v15", type: "vote", intensity: 5, vibes: ["incomodidad", "risas"], text: "Votación: ¿quién es más probable que se enamore esta noche (aunque sea 20 minutos)?", baseDrinks: 2, orientations: ROM, contentLevel: "medio" },
  { id: "v16", type: "vote", intensity: 4, vibes: ["competicion"], text: "Votación: ¿quién sobreviviría más días en un reality? El menos votado bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v17", type: "vote", intensity: 6, vibes: ["risas"], text: "Votación: ¿quién tiene el rincón más caótico del piso (aunque no lo hayamos visto)?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "v18", type: "vote", intensity: 5, vibes: ["nostalgia"], text: "Votación: ¿quién ha tenido la era más vergonzosa en fotos?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v19", type: "vote", intensity: 7, vibes: ["intimidad"], text: "Votación: ¿quién da más «te contaría un secreto a las 4»?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "v20", type: "vote", intensity: 6, vibes: ["locura", "risas"], text: "Votación: ¿quién debería llevar la corona de drama el resto de la noche?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "v21", type: "vote", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "Votación: ¿quién de esta mesa tiene más «ojo de tío» esta noche?", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "v22", type: "vote", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "Votación: ¿quién de esta mesa tiene más «ojo de tía» esta noche?", baseDrinks: 2, orientations: LES, contentLevel: "picante" },

  { id: "k13", type: "karaoke", intensity: 3, vibes: ["risas"], text: "{player}, canta el estribillo de un anuncio. Si no te acuerdas, inventa uno peor.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k14", type: "karaoke", intensity: 4, vibes: ["locura"], text: "{player}, canta «cumpleaños feliz» como villano de Disney.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k15", type: "karaoke", intensity: 5, vibes: ["competicion", "risas"], text: "{player} vs {other}: mismo estribillo. El grupo vota. Perdedor bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k16", type: "karaoke", intensity: 4, vibes: ["nostalgia"], text: "{player}, canta 15 segundos de una canción que ponían en bodas de pueblo.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k17", type: "karaoke", intensity: 6, vibes: ["risas"], text: "{player}, tararea una canción actual. El grupo tiene 3 intentos. Si no aciertan, bebes tú.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "k18", type: "karaoke", intensity: 7, vibes: ["locura"], text: "{player}, rap de 20 segundos usando solo palabras de esta mesa (nombres, copas, ruleta).", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k19", type: "karaoke", intensity: 5, vibes: ["risas", "nostalgia"], text: "{player}, canta el tema de una peli infantil como si fuera drama adolescente.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k20", type: "karaoke", intensity: 6, vibes: ["intimidad", "risas"], text: "{player}, dedica 15 segundos de balada a {other} como si fuera Eurovisión.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "k21", type: "karaoke", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, 20 segundos de tema de ligue lésbico dedicados a {other} (tú eliges).", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "k22", type: "karaoke", intensity: 7, vibes: ["locura", "risas"], text: "{player}, canta el estribillo más tóxico que recuerdes. El grupo puntúa el veneno.", baseDrinks: 2, orientations: N, contentLevel: "medio" },

  { id: "f13", type: "phone", intensity: 3, vibes: ["risas"], text: "{player}, enseña tu última captura de pantalla (tú eliges cuál si hay privadas).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f14", type: "phone", intensity: 4, vibes: ["risas"], text: "{player}, pon el teclado en mayúsculas y escribe un tuit imaginario de 10 palabras. Léelo.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f15", type: "phone", intensity: 5, vibes: ["incomodidad", "risas"], text: "{player}, enseña tus 3 emojis más usados. Defiende el combo.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f16", type: "phone", intensity: 5, vibes: ["nostalgia"], text: "{player}, muestra una foto de hace más de 3 años (tú eliges). El grupo pone título.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f17", type: "phone", intensity: 6, vibes: ["risas"], text: "{player}, cambia el nombre de {other} en tus contactos a lo que el grupo vote. 10 minutos.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f18", type: "phone", intensity: 6, vibes: ["locura"], text: "{player}, graba un audio de 8 segundos narrando esta ronda como documental. Solo se oye aquí.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f19", type: "phone", intensity: 7, vibes: ["incomodidad"], text: "{player}, deja que {other} elija UN sticker de tu teclado y lo enseñas. Veto libre.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "f20", type: "phone", intensity: 7, vibes: ["competicion", "risas"], text: "{player}, en 30 segundos encuentra en tu galería algo amarillo. Si no, bebes.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "f21", type: "phone", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, enseña (tú eliges) una conversación inocente. El grupo inventa el subtexto.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "f22", type: "phone", intensity: 6, vibes: ["risas"], text: "{player}, pon 10 segundos de la canción que tenías en shuffle. Sin saltar.", baseDrinks: 1, orientations: N, contentLevel: "suave" },

  { id: "cr08", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, dile a {other} un cumplido que no sea físico. Si te quedas en blanco, bebes.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "cr09", type: "couple", intensity: 6, vibes: ["intimidad"], text: "{player}, choca el meñique con {other} 10 segundos mirándoos. Quien suelte primero bebe.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "cr10", type: "couple", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, recuesta la cabeza 5 segundos en el hombro de {other} (ambos ok) o bebe.", baseDrinks: 1, orientations: ROM, contentLevel: "picante" },
  { id: "cr11", type: "couple", intensity: 8, vibes: ["intimidad"], text: "{player}, inventa una primera cita con {other} en 20 segundos. Si {other} dice «ni loco/a», bebes.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "cr12", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player} y {other}: 10 segundos de frente a frente a 20 cm (ambos ok). Si no, 2 tragos.", baseDrinks: 2, orientations: ROM, contentLevel: "sin_limite" },
  { id: "cg04", type: "couple", intensity: 6, vibes: ["intimidad", "risas"], text: "{player}, presenta a {other} como tu novio de peli gay en 15 segundos. Si se ríe, bebes tú.", baseDrinks: 1, orientations: GAY, contentLevel: "medio" },
  { id: "cg05", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, mano en la cintura de {other} 5 seg (ambos ok) con cara de after gay. Si no, 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "cl04", type: "couple", intensity: 6, vibes: ["intimidad", "risas"], text: "{player}, presenta a {other} como tu novia de peli lésbica en 15 segundos. Si se ríe, bebes tú.", baseDrinks: 1, orientations: LES, contentLevel: "medio" },
  { id: "cl05", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, mano en la cintura de {other} 5 seg (ambas ok) con cara de after lésbico. Si no, 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "ch04", type: "couple", intensity: 6, vibes: ["intimidad", "risas"], text: "{player}, presenta a {other} como tu crush de romcom hetero en 15 segundos. Si se ríe, bebes tú.", baseDrinks: 1, orientations: HET, contentLevel: "medio" },
  { id: "ch05", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, mano en la cintura de {other} 5 seg (ambos ok) vibe de primer ligue. Si no, 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "cb04", type: "couple", intensity: 7, vibes: ["intimidad"], text: "{player}, dile a {other} si esta noche te tira más su actitud «tío», «tía» o el combo.", baseDrinks: 2, orientations: BI, contentLevel: "picante" },
  { id: "cp04", type: "couple", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, describe a {other} en 3 palabras sin usar género. Solo vibra. Si fallas, bebes.", baseDrinks: 1, orientations: PAN, contentLevel: "picante" },

  { id: "s17", type: "strip", intensity: 5, vibes: ["risas"], text: "{player}, quítate un calcetín con ceremonia de Oscar. O bebe.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "s18", type: "strip", intensity: 6, vibes: ["risas", "locura"], text: "{player}, ponte las gafas / gorra / bufanda de {other} (si hay) 1 ronda. Si no hay, quita un accesorio tuyo.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "s19", type: "strip", intensity: 7, vibes: ["incomodidad", "risas"], text: "{player}, el grupo vota: ¿reloj, calcetín o trago? Tú ejecutas.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s20", type: "strip", intensity: 7, vibes: ["locura"], text: "{player}, quita una prenda de abrigo o capa extra. Si no llevas, 2 tragos y una pose.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s21", type: "strip", intensity: 8, vibes: ["competicion", "risas"], text: "{player} vs {other}: 8 segundos para quitar más accesorios. Quien quite menos bebe.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s22", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, 10 segundos de tease (nada se quita del todo). O 2 tragos.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },

  { id: "m21", type: "minigame", intensity: 3, vibes: ["competicion", "risas"], text: "Mini-juego: {player} y {other}, piedra-papel-tijera. El perdedor bebe y el ganador elige el siguiente tema de conversación 1 min.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m22", type: "minigame", intensity: 3, vibes: ["risas"], text: "Mini-juego: {player}, di 4 frutas sin repetir vocal en la primera letra. 8 segundos o bebes.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m23", type: "minigame", intensity: 4, vibes: ["risas", "nostalgia"], text: "Mini-juego: {player}, {other} imita un animal. Tú tienes 2 intentos para acertar.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m24", type: "minigame", intensity: 4, vibes: ["competicion"], text: "Mini-juego: {player}, cuenta 15 segundos en tu cabeza. El grupo cronometra. Si fallas más de 3 seg, bebes.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m25", type: "minigame", intensity: 5, vibes: ["risas"], text: "Mini-juego: {player}, no puedes usar la palabra «beber» ni «trago» hasta la siguiente ronda. Si fallas, bebes.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m26", type: "minigame", intensity: 5, vibes: ["locura", "risas"], text: "Mini-juego: {player}, di el abecedario al revés. Puedes parar en la P. Si te trabas antes, bebes.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m27", type: "minigame", intensity: 5, vibes: ["competicion"], text: "Mini-juego: {player} vs {other}: ¿quién nombra más ciudades en 10 segundos? El que menos, bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m28", type: "minigame", intensity: 6, vibes: ["risas"], text: "Mini-juego: {player}, ojos cerrados. El grupo cambia algo de la mesa. Abre y adivina. Si fallas, bebes.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m29", type: "minigame", intensity: 6, vibes: ["locura"], text: "Mini-juego: {player}, hasta la siguiente ronda hablas como si narraras un tutorial de YouTube.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m30", type: "minigame", intensity: 6, vibes: ["competicion", "risas"], text: "Mini-juego: {player}, lanza una moneda (o un tapón). Cara: bebes tú. Cruz: elige a {other}.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m31", type: "minigame", intensity: 7, vibes: ["locura", "risas"], text: "Mini-juego: {player}, categoría «cosas que hay en esta sala». 6 en 10 segundos o bebes.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m32", type: "minigame", intensity: 7, vibes: ["competicion"], text: "Mini-juego: {player} y {other}, pulgares arriba a la vez. El que tarde más bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
];

export function getAllChallenges(custom: Challenge[] = []): Challenge[] {
  return [...INITIAL_CHALLENGES, ...custom];
}
