import type { Challenge, OrientationPref } from "../../shared/types.js";

const N: OrientationPref[] = ["neutro"];
const GAY: OrientationPref[] = ["gay", "bi", "pan"];
const LES: OrientationPref[] = ["lesbiana", "bi", "pan"];
const HET: OrientationPref[] = ["hetero", "bi", "pan"];
const BI: OrientationPref[] = ["bi"];
const PAN: OrientationPref[] = ["pan"];
const ROM: OrientationPref[] = ["hetero", "gay", "lesbiana", "bi", "pan"];

/** Pack reetiquetado: el texto, el tipo, la orientación y el contentLevel coinciden. */
export const INITIAL_CHALLENGES: Challenge[] = [
  // === DRINK — el trago ES el reto (neutro salvo reglas explícitas) ===
  { id: "d01", type: "drink", intensity: 1, vibes: ["risas"], text: "{player}, brinda con {other} y di algo bonito (o falso, da igual).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d02", type: "drink", intensity: 2, vibes: ["risas", "competicion"], text: "{player}, si no puedes decir 3 países en 5 segundos, bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d03", type: "drink", intensity: 3, vibes: ["locura", "risas"], text: "{player}, bebe si alguna vez has mentido en este juego (spoiler: sí).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d04", type: "drink", intensity: 4, vibes: ["competicion"], text: "{player}, piedra-papel-tijera con {other}. El perdedor bebe doble.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "d05", type: "drink", intensity: 5, vibes: ["risas", "incomodidad"], text: "{player}, bebe cada vez que alguien diga tu nombre en los próximos 2 minutos.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "d06", type: "drink", intensity: 3, vibes: ["locura"], text: "{player}, bebe con la mano contraria a la que usas normalmente.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d07", type: "drink", intensity: 4, vibes: ["competicion", "risas"], text: "{player}, reto de miradas con {other}. El que parpadea primero bebe.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "d08", type: "drink", intensity: 6, vibes: ["locura", "competicion"], text: "{player}, bebe si no puedes mantener el equilibrio 10 seg con un pie.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "d09", type: "drink", intensity: 8, vibes: ["locura"], text: "{player}, shot de honor por el grupo. Sin excusas.", baseDrinks: 3, orientations: N, contentLevel: "medio" },
  { id: "d10", type: "drink", intensity: 7, vibes: ["locura", "competicion"], text: "{player}, bebe lo que el grupo decida. Democracia de copas.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d11", type: "drink", intensity: 3, vibes: ["nostalgia"], text: "{player}, bebe si extrañas algo de cuando eras más joven.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d12", type: "drink", intensity: 2, vibes: ["risas"], text: "{player}, bebe si has reído en los últimos 30 segundos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "d13", type: "drink", intensity: 5, vibes: ["competicion"], text: "{player} vs {other}: quien tenga menos tragos en stats bebe 2.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d14", type: "drink", intensity: 9, vibes: ["locura"], text: "{player}, mezcla lo que quieras en un vaso y bebe un trago (con sentido común).", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "d15", type: "drink", intensity: 6, vibes: ["incomodidad", "intimidad"], text: "{player}, bebe si esta noche te ha gustado alguien del grupo y no lo has dicho.", baseDrinks: 2, orientations: ROM, contentLevel: "medio" },
  { id: "d16", type: "drink", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, bebe si has tenido un crush con un tío de esta mesa (o con uno que os recuerde a alguien de aquí).", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "d17", type: "drink", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, bebe si has mirado más de la cuenta a una tía de esta mesa.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "d18", type: "drink", intensity: 10, vibes: ["locura", "competicion"], text: "{player}, todos los que estén por debajo de tu nivel te animan a beber. Tú decides cuánto.", baseDrinks: 3, orientations: N, contentLevel: "medio" },

  // === TRUTH ===
  { id: "t01", type: "truth", intensity: 1, vibes: ["risas", "nostalgia"], text: "{player}, ¿qué comida de la infancia volverías a comer ahora mismo?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t02", type: "truth", intensity: 2, vibes: ["risas"], text: "{player}, ¿qué superpoder inútil te gustaría tener?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t03", type: "truth", intensity: 3, vibes: ["incomodidad", "risas"], text: "{player}, ¿qué es lo más raro que has buscado en Google (versión apta para esta mesa)?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t04", type: "truth", intensity: 4, vibes: ["intimidad"], text: "{player}, ¿a quién del grupo le confiarías tu teléfono desbloqueado 1 minuto?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t05", type: "truth", intensity: 5, vibes: ["incomodidad"], text: "{player}, ¿qué mentira pequeña mantienes con alguien aquí?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "t06", type: "truth", intensity: 4, vibes: ["nostalgia"], text: "{player}, ¿qué canción te transporta a un momento concreto de tu vida?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t07", type: "truth", intensity: 4, vibes: ["risas"], text: "{player}, ¿qué personaje de ficción te representa cuando vas alto/a?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t08", type: "truth", intensity: 5, vibes: ["competicion"], text: "{player}, ¿quién del grupo crees que gana si hay pelea? Explica.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t09", type: "truth", intensity: 6, vibes: ["incomodidad"], text: "{player}, ¿has ghosteado a alguien? Cuenta la versión corta.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "t10", type: "truth", intensity: 4, vibes: ["nostalgia", "risas"], text: "{player}, ¿qué trend de internet te pareció una locura total?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t11", type: "truth", intensity: 5, vibes: ["risas"], text: "{player}, ¿qué opinión impopular tienes sobre comida?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "t12", type: "truth", intensity: 6, vibes: ["intimidad", "nostalgia"], text: "{player}, ¿cuál fue tu primer crush y qué edad tenías?", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "t13", type: "truth", intensity: 7, vibes: ["intimidad"], text: "{player}, ¿qué es lo que más te atrae de {other} (sin filtro de educación)?", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "t14", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, ¿qué valoras en alguien para algo más que amistad? Sé concreto.", baseDrinks: 1, orientations: ROM, contentLevel: "picante" },
  { id: "t15", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, describe tu tipo de chico con tres palabras atrevidas. O bebe.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "t16", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, describe tu tipo de chica con tres palabras atrevidas. O bebe.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "t17", type: "truth", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿tío o tía de esta mesa: a quién le harías el lío más peligroso y por qué?", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "t18", type: "truth", intensity: 9, vibes: ["intimidad"], text: "{player}, ¿con quién del grupo tendrías una cita si tuvieras que elegir? Di por qué sin esconderte.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "t19", type: "truth", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, cuenta tu lío gay más caótico (versión corta, sin doxxear a nadie que no esté aquí).", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },
  { id: "t20", type: "truth", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, cuenta tu lío con una tía más caótico (versión corta, sin doxxear a nadie que no esté aquí).", baseDrinks: 2, orientations: LES, contentLevel: "sin_limite" },
  { id: "t21", type: "truth", intensity: 10, vibes: ["intimidad", "incomodidad"], text: "{player}, ¿cuál es tu fantasía más random con un tío? Sin juicio (mentira, hay juicio).", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },
  { id: "t22", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, ¿te enrollarías con más de un género esta noche si el universo dijera sí? Explica sin ensayo.", baseDrinks: 2, orientations: BI, contentLevel: "picante" },
  { id: "t23", type: "truth", intensity: 8, vibes: ["intimidad"], text: "{player}, olvida etiquetas: ¿quién de esta mesa te pone más y por qué (actitud, no solo cara)?", baseDrinks: 2, orientations: PAN, contentLevel: "picante" },
  { id: "t24", type: "truth", intensity: 7, vibes: ["incomodidad", "risas"], text: "{player}, ¿qué app borrarías del teléfono de {other} sin que se enterara?", baseDrinks: 1, orientations: N, contentLevel: "medio" },

  // === PHYSICAL NEUTRO (acción corporal, cero romance) ===
  { id: "pn01", type: "physical", intensity: 2, vibes: ["risas", "competicion"], text: "{player}, 10 flexiones o bebe. Tu cuerpo decide.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "pn02", type: "physical", intensity: 3, vibes: ["locura", "risas"], text: "{player}, baila 20 segundos sin música. El grupo marca el ritmo a palmas.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn03", type: "physical", intensity: 3, vibes: ["risas"], text: "{player}, camina como si el suelo quemara hasta tu sitio.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn04", type: "physical", intensity: 4, vibes: ["nostalgia", "risas"], text: "{player}, recrea un baile de cuando eras adolescente. 15 segundos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "pn05", type: "physical", intensity: 5, vibes: ["locura", "competicion"], text: "{player}, mantén una postura ridícula 30 seg. Si te mueves, bebe.", baseDrinks: 2, orientations: N, contentLevel: "suave" },
  { id: "pn06", type: "physical", intensity: 4, vibes: ["risas"], text: "{player}, imita a {other} (voz y gestos) hasta que alguien acierte.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn07", type: "physical", intensity: 6, vibes: ["competicion"], text: "{player} vs {other}: abdominales en 30 seg. El que hace menos bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn08", type: "physical", intensity: 5, vibes: ["competicion"], text: "{player}, equilibra algo en la cabeza 15 seg (lo que sea seguro).", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn09", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, habla solo con gestos 1 minuto. Si hablas, bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn10", type: "physical", intensity: 7, vibes: ["competicion"], text: "{player}, salta lo más alto que puedas 5 veces seguidas.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn11", type: "physical", intensity: 8, vibes: ["risas", "locura"], text: "{player}, haz la voltereta o el intento más patético que puedas.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "pn12", type: "physical", intensity: 8, vibes: ["locura"], text: "{player}, 20 saltos de tijera o bebe el doble.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "pn13", type: "physical", intensity: 9, vibes: ["locura", "competicion"], text: "{player}, plank 45 segundos. Si caes, bebe y repites 15 seg.", baseDrinks: 3, orientations: N, contentLevel: "medio" },
  { id: "pn14", type: "physical", intensity: 6, vibes: ["locura"], text: "{player}, intenta tocar el suelo con las palmas sin doblar las rodillas.", baseDrinks: 2, orientations: N, contentLevel: "suave" },

  // === PHYSICAL GAY + PICANTE / SIN LÍMITE (acción + contexto gay de verdad) ===
  { id: "pg01", type: "physical", intensity: 6, vibes: ["locura", "intimidad"], text: "{player}, perrea 20 segundos como si {other} fuera el único tío que existe en la pista. Si te cortas, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg02", type: "physical", intensity: 7, vibes: ["locura", "risas"], text: "{player}, 12 sentadillas lentas y sucias. En cada una, un piropo de sauna a un chico del grupo (o al aire si no hay tíos).", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg03", type: "physical", intensity: 6, vibes: ["intimidad", "incomodidad"], text: "{player}, imita un ligue gay de after: mirada, sonrisa y mano en el hombro de {other} 5 seg. Si {other} dice no, solo la mirada.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg04", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, pose de calendario fitness 15 segundos. Actitud de camiseta mojada, camiseta puesta. Mira a los chicos.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg05", type: "physical", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, body roll + mirada pícara 10 segundos dedicados a {other}. Si te ríes, trago.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg06", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, 8 pasos de pasarela eligiendo arquetipo (twink, oso, daddy…) y desfila para los tíos de la mesa.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg07", type: "physical", intensity: 8, vibes: ["locura", "incomodidad"], text: "{player}, shirt-lift de 3 segundos (sube y baja la camiseta) mirando a {other}. O 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg08", type: "physical", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, baila pegado al aire 20 seg como si {other} te sujetara la cintura en un after.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg09", type: "physical", intensity: 8, vibes: ["competicion", "intimidad"], text: "{player}, plancha 20 seg. Mientras, di en voz alta tu tipo de chico con detalle. Si caes, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg10", type: "physical", intensity: 6, vibes: ["risas", "intimidad"], text: "{player}, recrea un primer beso de peli gay (con el aire o con tu mano). 10 segundos de drama.", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "pg11", type: "physical", intensity: 7, vibes: ["incomodidad", "locura"], text: "{player}, siéntate, ábrete de piernas, inclínate y dile a {other} «ven aquí» con la cabeza. Si no puedes de la risa, bebes.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg12", type: "physical", intensity: 8, vibes: ["locura", "competicion"], text: "{player}, 10 flexiones y en cada una un verbo atrevido que te gustaría oír de un tío. El grupo puntúa.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "pg13", type: "physical", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, slow-motion de quitar la camiseta SIN quitártela (el tease cuenta). 15 seg. O trago triple.", baseDrinks: 3, orientations: GAY, contentLevel: "sin_limite" },
  { id: "pg14", type: "physical", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, siéntate en el regazo de {other} 5 segundos (ambos ok) o 3 tragos. Actitud de ligue gay, no de IKEA.", baseDrinks: 3, orientations: GAY, contentLevel: "sin_limite" },

  // === PHYSICAL LESBIANA + PICANTE ===
  { id: "pl01", type: "physical", intensity: 6, vibes: ["locura", "intimidad"], text: "{player}, perrea 20 segundos como si {other} fuera la única tía de la pista. Si te cortas, bebes.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl02", type: "physical", intensity: 7, vibes: ["locura", "risas"], text: "{player}, 12 sentadillas lentas. En cada una, un piropo de bar a una chica del grupo (o al aire si no hay tías).", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl03", type: "physical", intensity: 6, vibes: ["intimidad", "incomodidad"], text: "{player}, imita un ligue lésbico de after: mirada, sonrisa y mano en el hombro de {other} 5 seg. Si dice no, solo la mirada.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl04", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, pose de portada soft 15 segundos. Actitud de «te como con los ojos». Mira a las chicas.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl05", type: "physical", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, body roll + mirada pícara 10 segundos dedicados a {other}. Si te ríes, trago.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl06", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, 8 pasos de pasarela eligiendo vibe (fem, butch, soft…) y desfila para las tías de la mesa.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl07", type: "physical", intensity: 8, vibes: ["locura", "incomodidad"], text: "{player}, sube el dobladillo o enseña un hombro 3 segundos mirando a {other}. O 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl08", type: "physical", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, baila pegada al aire 20 seg como si {other} te sujetara la cintura en un after.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl09", type: "physical", intensity: 8, vibes: ["competicion", "intimidad"], text: "{player}, plancha 20 seg. Mientras, di en voz alta tu tipo de chica con detalle. Si caes, bebes.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "pl10", type: "physical", intensity: 6, vibes: ["risas", "intimidad"], text: "{player}, recrea un primer beso de peli lésbica (con el aire o con tu mano). 10 segundos de drama.", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "pl11", type: "physical", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, tease de quitar una capa SIN quitártela 15 seg. O trago triple.", baseDrinks: 3, orientations: LES, contentLevel: "sin_limite" },
  { id: "pl12", type: "physical", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, siéntate en el regazo de {other} 5 segundos (ambas ok) o 3 tragos. Actitud de ligue, no de metro.", baseDrinks: 3, orientations: LES, contentLevel: "sin_limite" },

  // === PHYSICAL HETERO + PICANTE ===
  { id: "ph01", type: "physical", intensity: 6, vibes: ["locura", "intimidad"], text: "{player}, perrea 20 segundos mirando a alguien del género que te atrae en esta mesa. Si te cortas, bebes.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph02", type: "physical", intensity: 7, vibes: ["locura", "risas"], text: "{player}, 12 sentadillas lentas. En cada una, un piropo hetero de discoteca (el clásico malo cuenta).", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph03", type: "physical", intensity: 6, vibes: ["intimidad", "incomodidad"], text: "{player}, imita un ligue hetero de after: mirada, sonrisa y mano en el hombro de {other} 5 seg. Si dice no, solo la mirada.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph04", type: "physical", intensity: 7, vibes: ["locura", "intimidad"], text: "{player}, pose de anuncio de colonia 15 segundos. Mira a {other} como en un spot caro y tonto.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph05", type: "physical", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, body roll + mirada pícara 10 segundos dedicados a {other}. Si te ríes, trago.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph06", type: "physical", intensity: 6, vibes: ["locura", "risas"], text: "{player}, 8 pasos de pasarela «pareja de película hetero» y desfila para {other}.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph07", type: "physical", intensity: 8, vibes: ["locura", "incomodidad"], text: "{player}, shirt-lift o enseña un hombro 3 segundos mirando a {other}. O 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph08", type: "physical", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, baila pegado/a al aire 20 seg como si {other} te sujetara la cintura.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph09", type: "physical", intensity: 8, vibes: ["competicion", "intimidad"], text: "{player}, plancha 20 seg. Mientras, di tu tipo del género opuesto con detalle. Si caes, bebes.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "ph10", type: "physical", intensity: 6, vibes: ["risas", "intimidad"], text: "{player}, recrea un primer beso de romcom hetero (con el aire o con tu mano). 10 segundos.", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ph11", type: "physical", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, tease de quitar una capa SIN quitártela 15 seg. O trago triple.", baseDrinks: 3, orientations: HET, contentLevel: "sin_limite" },
  { id: "ph12", type: "physical", intensity: 9, vibes: ["intimidad", "incomodidad"], text: "{player}, siéntate en el regazo de {other} 5 segundos (ambos ok) o 3 tragos.", baseDrinks: 3, orientations: HET, contentLevel: "sin_limite" },

  // === VOTE ===
  { id: "v01", type: "vote", intensity: 2, vibes: ["risas"], text: "Votación: ¿quién es más probable que llegue tarde a su propia boda? El más votado bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v02", type: "vote", intensity: 3, vibes: ["risas", "competicion"], text: "Votación: ¿quién tiene el mejor sentido del humor de copas?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v03", type: "vote", intensity: 4, vibes: ["incomodidad", "risas"], text: "Votación: ¿quién es más probable que mande un mensaje de madrugada a un ex?", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "v04", type: "vote", intensity: 5, vibes: ["competicion"], text: "Votación: ¿quién ganaría en un concurso de comer rápido?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v05", type: "vote", intensity: 5, vibes: ["intimidad"], text: "Votación: ¿quién tiene más carisma sin esfuerzo?", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "v06", type: "vote", intensity: 4, vibes: ["nostalgia"], text: "Votación: ¿quién ha cambiado más desde que lo conocéis?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v07", type: "vote", intensity: 5, vibes: ["risas"], text: "Votación: ¿quién tiene el mejor y el peor gusto musical?", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "v08", type: "vote", intensity: 6, vibes: ["competicion"], text: "Votación: ¿quién del grupo es el más competitivo? (ironía pura).", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "v09", type: "vote", intensity: 7, vibes: ["intimidad", "risas"], text: "Votación: ¿quién es más guapo/a esta noche? (sin debate eterno).", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "v10", type: "vote", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "Votación: ¿quién daría el mejor ligue gay de esta mesa?", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "v11", type: "vote", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "Votación: ¿quién daría el mejor ligue lésbico de esta mesa?", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "v12", type: "vote", intensity: 6, vibes: ["locura"], text: "Votación: ¿quién debería ser el DJ del resto de la noche?", baseDrinks: 1, orientations: N, contentLevel: "suave" },

  // === KARAOKE ===
  { id: "k01", type: "karaoke", intensity: 2, vibes: ["risas", "nostalgia"], text: "{player}, canta el estribillo de la primera canción que te venga a la cabeza.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k02", type: "karaoke", intensity: 3, vibes: ["risas"], text: "{player}, canta «Feliz cumpleaños» como ópera.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k03", type: "karaoke", intensity: 4, vibes: ["locura", "risas"], text: "{player}, canta una canción inventada sobre {other}.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "k04", type: "karaoke", intensity: 5, vibes: ["competicion"], text: "{player}, duelo de canto con {other}. El grupo decide. Perdedor bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k05", type: "karaoke", intensity: 5, vibes: ["nostalgia"], text: "{player}, canta una canción de cuando tenías 15 años.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k06", type: "karaoke", intensity: 6, vibes: ["locura"], text: "{player}, canta el último mensaje de voz que recibiste (tono musical). Tú eliges cuál.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k07", type: "karaoke", intensity: 7, vibes: ["intimidad", "risas"], text: "{player}, canta una balada romántica mirando a {other}.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "k08", type: "karaoke", intensity: 8, vibes: ["locura"], text: "{player}, rap improvisado de 30 seg sobre esta fiesta.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k09", type: "karaoke", intensity: 4, vibes: ["risas"], text: "{player}, imita el estilo de canto de un artista famoso (sin decir quién).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k10", type: "karaoke", intensity: 5, vibes: ["nostalgia", "risas"], text: "{player}, canta el tema de una serie que veías de niño.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "k11", type: "karaoke", intensity: 7, vibes: ["locura", "risas"], text: "{player}, canta el estribillo de la canción más vergonzosa de tu playlist como si fueras de talent show.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "k12", type: "karaoke", intensity: 7, vibes: ["intimidad", "locura"], text: "{player}, canta 20 segundos de una canción de ligue gay (tú eliges) dedicándosela a {other}.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },

  // === PHONE (humor, sin doxxear a terceros inocentes) ===
  { id: "f01", type: "phone", intensity: 2, vibes: ["risas"], text: "{player}, muestra la foto más random de tu galería (sin explicar mucho).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f02", type: "phone", intensity: 3, vibes: ["risas"], text: "{player}, enseña tu fondo de pantalla y explica por qué (mentira permitida).", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f03", type: "phone", intensity: 4, vibes: ["risas"], text: "{player}, enseña la app que más usas y defiéndela como TED talk.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f04", type: "phone", intensity: 5, vibes: ["nostalgia"], text: "{player}, muestra la foto más antigua que tengas en el teléfono.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f05", type: "phone", intensity: 5, vibes: ["risas"], text: "{player}, cambia tu estado de WhatsApp a lo que el grupo decida por 10 min.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f06", type: "phone", intensity: 6, vibes: ["incomodidad", "risas"], text: "{player}, lee el nombre del último chat que TÚ elijas (no doxxees a alguien que no está).", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "f07", type: "phone", intensity: 7, vibes: ["incomodidad"], text: "{player}, muestra tu historial de búsqueda de hoy (o bebe si no quieres).", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "f08", type: "phone", intensity: 6, vibes: ["risas", "locura"], text: "{player}, graba un audio de 5 seg diciendo algo random. El grupo decide si lo envías al chat de ESTA fiesta.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "f09", type: "phone", intensity: 7, vibes: ["risas"], text: "{player}, selfie grupal con filtro absurdo. No subir obligatorio: solo enseñar.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "f10", type: "phone", intensity: 8, vibes: ["incomodidad"], text: "{player}, deja que {other} lea un mensaje que TÚ elijas de tu chat.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "f11", type: "phone", intensity: 7, vibes: ["competicion"], text: "{player}, el grupo pone timer: consigue 3 likes en una story en 2 min o bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "f12", type: "phone", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, enseña (tú eliges) una foto de galería que sea medio sospechosa. El grupo inventa el contexto.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },

  // === COUPLE — romance/contacto. Si coupleChallengesEnabled=false no salen. ===
  { id: "cr01", type: "couple", intensity: 4, vibes: ["intimidad"], text: "{player}, mira a {other} 15 seg sin hablar. Quien sonría primero bebe.", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "cr02", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, di 3 cosas que te gustan de {other} (sin repetir «eres majo»).", baseDrinks: 1, orientations: ROM, contentLevel: "medio" },
  { id: "cr03", type: "couple", intensity: 7, vibes: ["intimidad"], text: "{player}, masajea los hombros de {other} 15 segundos (ambos ok) o bebe.", baseDrinks: 1, orientations: ROM, contentLevel: "picante" },
  { id: "cr04", type: "couple", intensity: 8, vibes: ["intimidad", "risas"], text: "{player}, baila lento con {other} 30 seg (o lo que salga). Si no hay feeling, 2 tragos.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "cr05", type: "couple", intensity: 8, vibes: ["intimidad"], text: "{player}, beso en la mejilla de {other}. O bebe si el momento no da.", baseDrinks: 2, orientations: ROM, contentLevel: "picante" },
  { id: "cr06", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player}, body shot simulado con {other} (sin alcohol en cuerpos si no queréis). O 3 tragos.", baseDrinks: 3, orientations: ROM, contentLevel: "sin_limite" },
  { id: "cr07", type: "couple", intensity: 10, vibes: ["intimidad", "locura"], text: "{player}, lo que el grupo pida entre tú y {other}. Límite: lo que ambos acepten. Si no, 3 tragos.", baseDrinks: 3, orientations: ROM, contentLevel: "sin_limite" },

  { id: "cg01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, susurra al oído de {other} un piropo gay de discoteca. Si no se te ocurre, bebe.", baseDrinks: 1, orientations: GAY, contentLevel: "medio" },
  { id: "cg02", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, finge que {other} es tu crush de Grindr en una peli 15 seg (ambos ok).", baseDrinks: 1, orientations: GAY, contentLevel: "picante" },
  { id: "cg03", type: "couple", intensity: 9, vibes: ["intimidad"], text: "{player}, elige con {other}: beso (lo que ambos acepten), verdad sucia de tíos o 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "sin_limite" },

  { id: "cl01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, susurra al oído de {other} un piropo de tía a tía. Si no se te ocurre, bebe.", baseDrinks: 1, orientations: LES, contentLevel: "medio" },
  { id: "cl02", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, finge que {other} es tu crush de un after lésbico 15 seg (ambas ok).", baseDrinks: 1, orientations: LES, contentLevel: "picante" },
  { id: "cl03", type: "couple", intensity: 9, vibes: ["intimidad"], text: "{player}, elige con {other}: beso (lo que ambas acepten), verdad sucia de tías o 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "sin_limite" },

  { id: "ch01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, susurra a {other} un piropo hetero de mal gusto a propósito. Si flipa, bebes tú.", baseDrinks: 1, orientations: HET, contentLevel: "medio" },
  { id: "ch02", type: "couple", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, finge que {other} es tu crush de romcom 15 seg (ambos ok).", baseDrinks: 1, orientations: HET, contentLevel: "picante" },
  { id: "ch03", type: "couple", intensity: 9, vibes: ["intimidad"], text: "{player}, elige con {other}: beso (lo que ambos acepten), verdad sucia hetero o 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "sin_limite" },

  { id: "cb01", type: "couple", intensity: 5, vibes: ["intimidad"], text: "{player}, dile a {other} qué género te come más la cabeza esta noche. Sin ensayo.", baseDrinks: 1, orientations: BI, contentLevel: "medio" },
  { id: "cb02", type: "couple", intensity: 8, vibes: ["intimidad", "incomodidad"], text: "{player}, elige a {other} y di en voz alta si tu crush de ahora es más «tío», «tía» o «las dos cosas».", baseDrinks: 2, orientations: BI, contentLevel: "picante" },
  { id: "cb03", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player} y {other}: 20 seg de flirteo sin importar género. Si os cortáis, 2 tragos.", baseDrinks: 2, orientations: BI, contentLevel: "sin_limite" },

  { id: "cp01", type: "couple", intensity: 5, vibes: ["intimidad", "risas"], text: "{player}, ignora etiquetas y dile a {other} qué te atrae de su forma de estar.", baseDrinks: 1, orientations: PAN, contentLevel: "medio" },
  { id: "cp02", type: "couple", intensity: 8, vibes: ["intimidad"], text: "{player}, flirtea 15 seg con {other} como si el género no existiera. Solo vibra.", baseDrinks: 1, orientations: PAN, contentLevel: "picante" },
  { id: "cp03", type: "couple", intensity: 9, vibes: ["intimidad", "locura"], text: "{player} y {other}: el grupo pide un gesto atrevido. Solo si ambos aceptan; si no, 2 tragos.", baseDrinks: 2, orientations: PAN, contentLevel: "sin_limite" },

  // === STRIP ===
  { id: "s01", type: "strip", intensity: 5, vibes: ["risas", "incomodidad"], text: "{player}, quita un accesorio (reloj, calcetín, gorra…). O bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "s02", type: "strip", intensity: 5, vibes: ["risas"], text: "{player}, quita los zapatos de forma cinematográfica.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "s03", type: "strip", intensity: 6, vibes: ["risas"], text: "{player}, ponte 1 prenda de {other} encima de la tuya.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "s04", type: "strip", intensity: 6, vibes: ["risas", "locura"], text: "{player}, cambia una prenda con {other} (accesorio vale). Sin drama.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "s05", type: "strip", intensity: 7, vibes: ["incomodidad", "risas"], text: "{player}, quita la capa de ropa que el grupo vote. Consentimiento primero; si no, 2 tragos.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s06", type: "strip", intensity: 8, vibes: ["locura", "intimidad"], text: "{player}, strip de una prenda con la máxima dramaturgia posible. O bebe.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s07", type: "strip", intensity: 7, vibes: ["competicion", "risas"], text: "{player} vs {other}: quien se quite más accesorios en 10 seg gana. Perdedor bebe.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s08", type: "strip", intensity: 8, vibes: ["incomodidad"], text: "{player}, describe tu outfit como pasarela. El grupo decide si quitas algo o bebes.", baseDrinks: 2, orientations: N, contentLevel: "picante" },
  { id: "s09", type: "strip", intensity: 9, vibes: ["locura"], text: "{player}, ruleta mental: una capa de ropa o trago triple.", baseDrinks: 3, orientations: N, contentLevel: "sin_limite" },
  { id: "s10", type: "strip", intensity: 10, vibes: ["locura", "competicion"], text: "{player}, el grupo cuenta capas. Quitas N o bebes N tragos. Tú pones el límite.", baseDrinks: 2, orientations: N, contentLevel: "sin_limite" },
  { id: "s11", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, {other} elige qué prenda quitas o qué bebes. Veto libre.", baseDrinks: 3, orientations: ROM, contentLevel: "sin_limite" },
  { id: "s12", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, baile de strip 15 seg para los tíos de la mesa o 2 tragos.", baseDrinks: 2, orientations: GAY, contentLevel: "picante" },
  { id: "s13", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, baile de strip 15 seg para las tías de la mesa o 2 tragos.", baseDrinks: 2, orientations: LES, contentLevel: "picante" },
  { id: "s14", type: "strip", intensity: 8, vibes: ["intimidad", "locura"], text: "{player}, baile de strip 15 seg dedicado a {other} (vibe hetero) o 2 tragos.", baseDrinks: 2, orientations: HET, contentLevel: "picante" },
  { id: "s15", type: "strip", intensity: 9, vibes: ["locura", "intimidad"], text: "{player}, quita una prenda como si estuvieras en un after gay. O 3 tragos.", baseDrinks: 3, orientations: GAY, contentLevel: "sin_limite" },
  { id: "s16", type: "strip", intensity: 9, vibes: ["locura", "intimidad"], text: "{player}, quita una prenda como si estuvieras en un after lésbico. O 3 tragos.", baseDrinks: 3, orientations: LES, contentLevel: "sin_limite" },

  // === MINIGAME — reglas claras, tags honestos (NO gay/físico/picante de mentira) ===
  { id: "m01", type: "minigame", intensity: 2, vibes: ["competicion", "risas"], text: "Mini-juego: {player} y {other}, piedra-papel-tijera al mejor de 3. Perdedor bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m02", type: "minigame", intensity: 3, vibes: ["competicion"], text: "Mini-juego: {player}, di un color. {other} dice animal. Tú un país. Sin pensar. Si tardas, bebes.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m03", type: "minigame", intensity: 3, vibes: ["risas"], text: "Mini-juego: todos a la vez, sacad la lengua. El último bebe.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m04", type: "minigame", intensity: 4, vibes: ["risas", "nostalgia"], text: "Mini-juego: {player}, adivina la canción que {other} tararea.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m05", type: "minigame", intensity: 3, vibes: ["risas"], text: "Mini-juego: {player}, di «ruleta del trago» entre cada palabra durante 30 seg.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m06", type: "minigame", intensity: 4, vibes: ["nostalgia", "risas"], text: "Mini-juego: {player}, adivina qué serie veía {other} de niño con 3 pistas.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m07", type: "minigame", intensity: 4, vibes: ["risas"], text: "Mini-juego: {player}, imita un videojuego clásico solo con sonidos.", baseDrinks: 1, orientations: N, contentLevel: "suave" },
  { id: "m08", type: "minigame", intensity: 5, vibes: ["competicion", "risas"], text: "Mini-juego: {player} vs {other}, pulgar a pulgar. 3 rondas.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m09", type: "minigame", intensity: 5, vibes: ["competicion", "locura"], text: "Mini-juego: {player}, aguanta 20 seg con un cubito en la mano o bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m10", type: "minigame", intensity: 5, vibes: ["risas"], text: "Mini-juego: {player}, ojos cerrados, identifica a {other} solo por la voz.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m11", type: "minigame", intensity: 5, vibes: ["competicion"], text: "Mini-juego: {player}, el grupo pide tocarse nariz, oreja, codo… sin manos. 20 seg.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m12", type: "minigame", intensity: 6, vibes: ["risas", "locura"], text: "Mini-juego: {player}, cuenta hasta 20 sustituyendo los múltiplos de 3 por «ruleta».", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m13", type: "minigame", intensity: 6, vibes: ["competicion", "risas"], text: "Mini-juego: {player}, lanza algo blando al aire. Acierta dónde dice el grupo o bebe.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m14", type: "minigame", intensity: 6, vibes: ["risas", "competicion"], text: "Mini-juego: {player} vs todos. Tú lanzas un «yo nunca» de fiesta light. Si alguien ya lo hizo, bebe. Si nadie, tú.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m15", type: "minigame", intensity: 6, vibes: ["locura"], text: "Mini-juego: {player}, no puedes tocar tu vaso con la mano derecha hasta la siguiente ronda.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m16", type: "minigame", intensity: 7, vibes: ["locura"], text: "Mini-juego: {player}, habla con voz de robot hasta la siguiente ronda.", baseDrinks: 1, orientations: N, contentLevel: "medio" },
  { id: "m17", type: "minigame", intensity: 7, vibes: ["competicion"], text: "Mini-juego: cuenta atrás de 10. {player} y {other} a la vez. Quien llegue a 0 primero gana; el otro bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m18", type: "minigame", intensity: 7, vibes: ["locura", "risas"], text: "Mini-juego: {player}, categoría random. 5 cosas en 10 segundos o bebes.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m19", type: "minigame", intensity: 8, vibes: ["competicion", "locura"], text: "Mini-juego: todos. Manos al centro, el último en quitar bebe. {player} da la señal.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
  { id: "m20", type: "minigame", intensity: 8, vibes: ["locura", "risas"], text: "Mini-juego: todos copian el movimiento de {player}. El que se ría bebe.", baseDrinks: 2, orientations: N, contentLevel: "medio" },
];

export function getAllChallenges(custom: Challenge[] = []): Challenge[] {
  return [...INITIAL_CHALLENGES, ...custom];
}
